FROM python:3.10

WORKDIR /operationsservice

COPY .env ./
COPY .gitignore ./
COPY requirements.txt ./
COPY src ./src

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5200

CMD ["python", "src/main.py"]